name: Static Website CI

on:
  push:
    branches: 
    - master
    tags:
    - v0.*
    - v1.*
    - v2.*
  pull_request:
    branches: 
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Image
      uses: docker/build-push-action@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: dtlaboratory/dtlab-nginx-redirect
        tag_with_ref: true
        tag_with_sha: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
